# Generated by Django 5.0.7 on 2025-08-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('sector', models.CharField(choices=[('Roads', 'Roads'), ('Metro', 'Metro'), ('Bridges', 'Bridges'), ('Smart City', 'Smart City'), ('Beautification', 'Beautification'), ('Redevelopment', 'Redevelopment'), ('Waste Management', 'Waste Management'), ('Water Supply', 'Water Supply'), ('Green Spaces', 'Green Spaces'), ('Transport', 'Transport'), ('Railways', 'Railways'), ('Eco-Tourism', 'Eco-Tourism'), ('Ports', 'Ports'), ('Airport', 'Airport')], max_length=50)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], max_length=20)),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.CharField(max_length=200)),
                ('progress', models.IntegerField()),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
