# Generated by Django 5.0.7 on 2025-08-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroConstructionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Under Construction', 'Under Construction'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], max_length=20)),
                ('estimated_completion', models.DateField()),
                ('current_progress', models.CharField(max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-estimated_completion'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBottleneck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottleneck_id', models.CharField(max_length=20, unique=True)),
                ('project_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('bottleneck_type', models.CharField(max_length=100)),
                ('severity_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('reported_date', models.DateField()),
                ('expected_resolution_date', models.DateField()),
                ('responsible_department', models.CharField(max_length=100)),
                ('current_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Pending', 'Pending')], max_length=20)),
                ('impact_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='RoadDevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('road_length', models.DecimalField(decimal_places=2, max_digits=8)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('current_status', models.CharField(choices=[('Planning', 'Planning'), ('Under Construction', 'Under Construction'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], max_length=20)),
                ('contractor', models.CharField(max_length=200)),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
